replicaCount: 1

image:
  repository: ghcr.io/maxpal-gh/flask-color-api
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 5000 # This is the port your application inside the container listens on

service:
  type: ClusterIP # Can be ClusterIP, NodePort, LoadBalancer
  port: 5000         # This is the port the service will expose