image:
  repository: ghcr.io/maxpal-gh/flask-color-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  containerPort: 5000
  nodePort: 30500
  port: 5000

serviceAccount: 
  create: true