apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maxpal-gh/docker-helm.git
    targetRevision: main
    path: helm/flask-color-chart
    helm:
      values: |
        image:
          repository: ghcr.io/maxpal-gh/flask-color-api
          tag: 29
          pullPolicy: IfNotPresent

        service:
          type: NodePort
          containerPort: 5000
          nodePort: 30500
          port: 5000

        serviceAccount: 
          create: true
        replicaCount: 10
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
